<h1>Book: <?=$book[0]['title']?></h1>


<h2 class="flash"><?=Session::getFlash();?></h2>
<br>
Author:  <?php foreach($book as $author){?>

<a href="/author-<?=$author['author']?>">



        <?php echo $author['author_name'];}?>
    <br></a>
Title:  <?=$book[0]['title']?><br>
Description - <?=$book[0]['description']?><br>
Price:  <?=$book[0]['price']?><br>



<a href="/add/<?=$book[0]['id']?>">Add to cart</a>
<br>
<br>

<a href="/books"><button>Back</button></a><br>

